#!/bin/bash
#
# Quick Configuration Setup Script
# This interactive script helps you configure log rotation paths

echo "=========================================="
echo "  Log Rotation Configuration Setup"
echo "=========================================="
echo
echo "This script will help you configure:"
echo "  1. Location of your access log file"
echo "  2. Location for backup/rotated logs"
echo "  3. Optional archive location"
echo
echo "Current configuration will be saved to: logrotate.config"
echo

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/logrotate.config"

# Check if config exists
if [ -f "$CONFIG_FILE" ]; then
    echo "⚠ Configuration file already exists!"
    echo "Current settings:"
    echo "---"
    grep "^LOG_FILE=" "$CONFIG_FILE" || echo "LOG_FILE not found"
    grep "^BACKUP_DIR=" "$CONFIG_FILE" || echo "BACKUP_DIR not found"
    echo "---"
    echo
    read -p "Do you want to overwrite it? (y/n): " overwrite
    if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
        echo "Configuration unchanged. Exiting."
        exit 0
    fi
    echo
fi

# === LOG FILE LOCATION ===
echo "=== Step 1: Access Log Location ==="
echo
read -p "Enter the full path to your access log file [/hw00/d19/x/access_log]: " log_file
LOG_FILE=${log_file:-/hw00/d19/x/access_log}

# Validate log file
if [ ! -f "$LOG_FILE" ]; then
    echo "⚠ Warning: Log file does not exist: $LOG_FILE"
    read -p "Continue anyway? (y/n): " continue_log
    if [ "$continue_log" != "y" ] && [ "$continue_log" != "Y" ]; then
        echo "Exiting."
        exit 1
    fi
fi

echo "✓ Log file set to: $LOG_FILE"
echo

# === BACKUP DIRECTORY ===
echo "=== Step 2: Backup/Rotated Logs Location ==="
echo
echo "Options:"
echo "  1. Same directory as log file: $(dirname "$LOG_FILE")"
echo "  2. Custom location (you specify)"
echo
read -p "Choose option (1 or 2) [2]: " backup_choice
backup_choice=${backup_choice:-2}

if [ "$backup_choice" = "1" ]; then
    BACKUP_DIR="$(dirname "$LOG_FILE")"
else
    read -p "Enter backup directory path [$HOME/log-backups]: " backup_dir
    BACKUP_DIR=${backup_dir:-$HOME/log-backups}
fi

# Create backup directory if it doesn't exist
if [ ! -d "$BACKUP_DIR" ]; then
    echo "Creating backup directory: $BACKUP_DIR"
    mkdir -p "$BACKUP_DIR" || {
        echo "ERROR: Cannot create backup directory"
        exit 1
    }
fi

echo "✓ Backup directory set to: $BACKUP_DIR"
echo

# === ARCHIVE SETTINGS ===
echo "=== Step 3: Archive Settings (Optional) ==="
echo
read -p "Do you want to use a separate archive location? (y/n) [n]: " use_archive
use_archive=${use_archive:-n}

if [ "$use_archive" = "y" ] || [ "$use_archive" = "Y" ]; then
    read -p "Enter archive directory path [$HOME/log-archive]: " archive_dir
    ARCHIVE_DIR=${archive_dir:-$HOME/log-archive}
    
    read -p "Keep how many recent logs in backup dir? [7]: " keep_recent
    KEEP_RECENT=${keep_recent:-7}
    
    read -p "Keep archived logs for how many days? [90]: " archive_days
    ARCHIVE_DAYS=${archive_days:-90}
    
    mkdir -p "$ARCHIVE_DIR" 2>/dev/null
    echo "✓ Archive directory: $ARCHIVE_DIR"
    echo "✓ Keep recent: $KEEP_RECENT"
    echo "✓ Archive retention: $ARCHIVE_DAYS days"
else
    ARCHIVE_DIR="$HOME/log-archive"
    KEEP_RECENT=7
    ARCHIVE_DAYS=90
    echo "✓ Using default archive settings"
fi
echo

# === RETENTION ===
echo "=== Step 4: Retention Settings ==="
echo
read -p "How many rotated logs to keep? [7]: " keep_count
KEEP_COUNT=${keep_count:-7}

read -p "Maximum log size in MB (for size-based rotation)? [100]: " max_size
MAX_SIZE=${max_size:-100}

echo "✓ Keep count: $KEEP_COUNT"
echo "✓ Max size: ${MAX_SIZE}MB"
echo

# === COMPRESSION ===
echo "=== Step 5: Compression ==="
echo
echo "Available compression tools:"
if command -v gzip &> /dev/null; then echo "  - gzip (fast, good compression)"; fi
if command -v bzip2 &> /dev/null; then echo "  - bzip2 (slower, better compression)"; fi
if command -v xz &> /dev/null; then echo "  - xz (slowest, best compression)"; fi
echo "  - none (no compression)"
echo
read -p "Choose compression tool [gzip]: " compression
COMPRESSION=${compression:-gzip}

echo "✓ Compression: $COMPRESSION"
echo

# === GENERATE CONFIG FILE ===
echo "=== Generating Configuration File ==="
echo

cat > "$CONFIG_FILE" << EOF
#!/bin/bash
#
# Log Rotation Configuration File
# Generated by configure-logrotate.sh on $(date)
#

# ============================================================
# PRIMARY LOG FILE CONFIGURATION
# ============================================================

LOG_FILE="$LOG_FILE"
LOG_DIR="\$(dirname "\$LOG_FILE")"

# ============================================================
# BACKUP/ROTATED LOGS CONFIGURATION
# ============================================================

BACKUP_DIR="$BACKUP_DIR"

# ============================================================
# ROTATION SETTINGS
# ============================================================

DEFAULT_KEEP_COUNT=$KEEP_COUNT
DEFAULT_MAX_SIZE_MB=$MAX_SIZE

# ============================================================
# ARCHIVE SETTINGS
# ============================================================

ARCHIVE_DIR="$ARCHIVE_DIR"
ARCHIVE_KEEP_RECENT=$KEEP_RECENT
ARCHIVE_RETENTION_DAYS=$ARCHIVE_DAYS

# ============================================================
# COMPRESSION SETTINGS
# ============================================================

COMPRESSION_TOOL="$COMPRESSION"
GZIP_LEVEL=6

# ============================================================
# NAMING SETTINGS
# ============================================================

TIMESTAMP_FORMAT="%Y%m%d-%H%M%S"

# ============================================================
# LOGGING
# ============================================================

ROTATION_LOG="\$HOME/logrotate.log"

# ============================================================
# VALIDATION
# ============================================================

if [ -z "\$LOG_FILE" ]; then
    echo "ERROR: LOG_FILE is not set in configuration"
    exit 1
fi

if [ -z "\$BACKUP_DIR" ]; then
    echo "ERROR: BACKUP_DIR is not set in configuration"
    exit 1
fi

if [ ! -d "\$BACKUP_DIR" ]; then
    mkdir -p "\$BACKUP_DIR" || {
        echo "ERROR: Cannot create backup directory: \$BACKUP_DIR"
        exit 1
    }
fi

export LOG_FILE LOG_DIR BACKUP_DIR
export DEFAULT_KEEP_COUNT DEFAULT_MAX_SIZE_MB
export ARCHIVE_DIR ARCHIVE_KEEP_RECENT ARCHIVE_RETENTION_DAYS
export COMPRESSION_TOOL GZIP_LEVEL TIMESTAMP_FORMAT ROTATION_LOG
EOF

echo "✓ Configuration file created: $CONFIG_FILE"
echo

# === SUMMARY ===
echo "=========================================="
echo "  Configuration Summary"
echo "=========================================="
echo
echo "Log file:        $LOG_FILE"
echo "Backup directory: $BACKUP_DIR"
echo "Archive directory: $ARCHIVE_DIR"
echo "Keep count:      $KEEP_COUNT rotations"
echo "Max size:        ${MAX_SIZE}MB"
echo "Compression:     $COMPRESSION"
echo
echo "Configuration saved to: $CONFIG_FILE"
echo
echo "=========================================="
echo "  Next Steps"
echo "=========================================="
echo
echo "Test your configuration:"
echo "  ./rotate-access-log.sh"
echo
echo "Set up automated rotation:"
echo "  ./setup-cron.sh"
echo
echo "View/edit configuration:"
echo "  nano $CONFIG_FILE"
echo
